server:
  internalPort: ${Deploy:Port}
  runMode: release
  staticContentPath: './public'
  apiUrl: ${Deploy:ApiUrl}
logger:
  filePath: ${Deploy:RootFolder}
  encoding: json
  level: debug
  logger: zap